import type {
  Activity,
  LearningCheck,
  LearningPlan,
  Learner,
  ProgressEntry,
  Report,
  Session,
} from "./types";

export const GRADES = ["Grade R", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7"];

export const SKILLS: Record<"Literacy" | "Mathematics", string[]> = {
  Literacy: [
    "Letter recognition",
    "Letter sounds",
    "Phonological awareness",
    "Phonics",
    "Blending",
    "Reading",
    "Reading fluency",
    "Reading comprehension",
    "Spelling",
    "Writing",
    "Handwriting",
  ],
  Mathematics: [
    "Number recognition",
    "Counting",
    "Number sense",
    "Place value",
    "Addition",
    "Subtraction",
    "Multiplication",
    "Division",
    "Problem-solving",
  ],
};

export const LITERACY_CHECK_ITEMS = [
  "Letter recognition",
  "Letter sounds",
  "Phonological awareness",
  "Phonics",
  "Reading",
  "Reading fluency",
  "Reading comprehension",
  "Spelling",
  "Writing",
];

export const MATHS_CHECK_ITEMS = [
  "Number recognition",
  "Counting",
  "Number sense",
  "Place value",
  "Basic operations",
  "Problem-solving",
];

export const OBSERVATION_ITEMS = [
  "Attention",
  "Confidence",
  "Persistence",
  "Response time",
  "Prompting required",
  "Self-correction",
  "Strategies used",
  "General observations",
];

export const ACTIVITY_TYPES = [
  "Matching",
  "Flashcards",
  "Word building",
  "Sorting",
  "Reading practice",
  "Writing practice",
  "Number games",
  "Problem-solving",
  "Interactive practice",
];

export const DIFFICULTIES = ["Beginning", "Developing", "Consolidating"];

export const demoLearners: Learner[] = [
  {
    id: "l1",
    name: "Amara M.",
    grade: "Grade 2",
    school: "Sunrise Primary",
    age: 8,
    guardian: "Ms. Mokoena (mother)",
    guardianContact: "amara.parent@example.com",
    format: "In person, small group",
    focus: "Literacy — phonics & blending",
    subject: "Literacy",
    progress: 68,
    lastSession: "17 Aug 2026",
    status: "On track",
    strengths: ["Strong listening comprehension", "Recognises all capital letters", "Enjoys shared reading"],
    growth: ["Blending three-sound words", "Letter reversals (b/d)", "Spelling of high-frequency words"],
    goals: ["Blend CVC words with 80% accuracy", "Write 10 high-frequency words from memory"],
  },
  {
    id: "l2",
    name: "Liam D.",
    grade: "Grade 4",
    school: "Hillcrest Primary",
    age: 10,
    guardian: "Mr. Daniels (father)",
    guardianContact: "liam.parent@example.com",
    format: "One-on-one, afternoons",
    focus: "Mathematics — place value",
    subject: "Mathematics",
    progress: 45,
    lastSession: "18 Aug 2026",
    status: "Needs attention",
    strengths: ["Confident counting in 2s and 5s", "Good mental addition to 20", "Persists with concrete materials"],
    growth: ["Place value to 1 000", "Subtraction with borrowing", "Multi-step word problems"],
    goals: ["Represent 3-digit numbers using base-ten blocks", "Solve 2-step word problems with support"],
  },
  {
    id: "l3",
    name: "Naledi K.",
    grade: "Grade 3",
    school: "Sunrise Primary",
    age: 9,
    guardian: "Mrs. Khumalo (mother)",
    guardianContact: "naledi.parent@example.com",
    format: "In person, weekly",
    focus: "Reading fluency & comprehension",
    subject: "Literacy",
    progress: 74,
    lastSession: "15 Aug 2026",
    status: "On track",
    strengths: ["Decodes accurately", "Rich vocabulary", "Self-corrects when reading aloud"],
    growth: ["Reading pace and expression", "Inferential comprehension", "Written responses"],
    goals: ["Read 70 words per minute with expression", "Answer 3 inference questions per passage"],
  },
  {
    id: "l4",
    name: "Sipho T.",
    grade: "Grade R",
    school: "Little Steps Pre-Primary",
    age: 6,
    guardian: "Ms. Tshabalala (aunt)",
    guardianContact: "sipho.parent@example.com",
    format: "In person, play-based",
    focus: "Letter recognition",
    subject: "Literacy",
    progress: 32,
    lastSession: "12 Aug 2026",
    status: "New",
    strengths: ["Loves rhymes and songs", "Strong fine-motor play", "Follows two-step instructions"],
    growth: ["Recognising lowercase letters", "Hearing initial sounds", "Pencil grip"],
    goals: ["Recognise 12 lowercase letters", "Identify initial sounds in 5 familiar words"],
  },
  {
    id: "l5",
    name: "Zanele P.",
    grade: "Grade 6",
    school: "Hillcrest Primary",
    age: 12,
    guardian: "Mr. Pillay (father)",
    guardianContact: "zanele.parent@example.com",
    format: "Online, twice weekly",
    focus: "Mathematics — problem-solving",
    subject: "Mathematics",
    progress: 58,
    lastSession: "19 Aug 2026",
    status: "On track",
    strengths: ["Knows times tables to 8", "Neat, organised working", "Asks clarifying questions"],
    growth: ["Division with remainders", "Choosing a strategy for word problems", "Fraction comparison"],
    goals: ["Solve division word problems using a chosen strategy", "Compare fractions with unlike denominators"],
  },
];

export const demoSessions: Session[] = [
  { id: "s1", learnerId: "l2", date: "20 Aug 2026", time: "14:00", focus: "Place value to 1 000" },
  { id: "s2", learnerId: "l1", date: "20 Aug 2026", time: "15:30", focus: "Blending CVC words" },
  { id: "s3", learnerId: "l5", date: "21 Aug 2026", time: "16:00", focus: "Division word problems" },
  { id: "s4", learnerId: "l3", date: "22 Aug 2026", time: "09:00", focus: "Reading fluency practice" },
  { id: "s5", learnerId: "l4", date: "24 Aug 2026", time: "10:00", focus: "Lowercase letter play" },
];

export const demoChecks: LearningCheck[] = [
  {
    id: "c1",
    learnerId: "l1",
    date: "10 Aug 2026",
    literacy: { "Letter recognition": 4, "Letter sounds": 3, Phonics: 2, Reading: 2, Spelling: 2 },
    mathematics: { Counting: 4, "Number sense": 3 },
    observation: { Attention: "Focused for 10–15 minutes", Confidence: "Hesitant when reading aloud" },
    notes: "Amara engages well with picture support. Needs modelling before independent blending.",
  },
  {
    id: "c2",
    learnerId: "l2",
    date: "11 Aug 2026",
    literacy: { Reading: 4, "Reading comprehension": 3 },
    mathematics: { "Place value": 2, "Basic operations": 2, "Problem-solving": 2 },
    observation: { Persistence: "Keeps trying with concrete apparatus", "Prompting required": "Moderate" },
    notes: "Liam benefits from base-ten blocks and verbalising each step.",
  },
];

export const demoPlans: LearningPlan[] = [
  {
    id: "p1",
    learnerId: "l1",
    created: "11 Aug 2026",
    reviewDate: "22 Sep 2026",
    priorityAreas: "Blending CVC words; letter discrimination (b/d); high-frequency word spelling",
    currentLevel: "Recognises all letter names; blends 2-sound words with modelling",
    goals:
      "1. Blend 8 of 10 CVC words independently.\n2. Correctly form b and d in 9 of 10 attempts.\n3. Spell 10 high-frequency words from memory.",
    activities: "Sound-box word building; b/d sorting with tactile cards; word-family flashcards; paired reading",
    frequency: "Three 30-minute sessions per week",
    indicators: "Weekly CVC word check; error count on b/d sort; spelling of the weekly word list",
  },
  {
    id: "p2",
    learnerId: "l2",
    created: "12 Aug 2026",
    reviewDate: "25 Sep 2026",
    priorityAreas: "Place value to 1 000; subtraction with borrowing; two-step word problems",
    currentLevel: "Reads and writes 2-digit numbers confidently; regroups with support",
    goals:
      "1. Represent 3-digit numbers with base-ten blocks in 4 of 5 tasks.\n2. Complete subtraction with regrouping with one prompt or fewer.\n3. Solve two-step word problems using a drawn model.",
    activities: "Base-ten block builds; place-value dice game; bar-model problem cards; number-line jumps",
    frequency: "Two 45-minute sessions per week",
    indicators: "Fortnightly place-value check; prompts needed per task; accuracy on problem cards",
  },
];

export const demoActivities: Activity[] = [
  {
    id: "a1",
    title: "Sound Boxes: Building CVC Words",
    grade: "Grade 2",
    subject: "Literacy",
    skill: "Blending",
    difficulty: "Developing",
    type: "Word building",
    content:
      "Learning objective\nThe learner blends three sounds to read and build CVC words.\n\nMaterials required\nRecycled cardboard sound-box strips, bottle-top letter tiles, word list.\n\nInstructions\n1. Say a word slowly (c-a-t) and ask the learner to push one tile into each box.\n2. The learner sweeps a finger under the boxes and reads the whole word.\n3. Change one sound at a time (cat → cap → cup) and reread.\n\nExample questions\ncat, map, tin, hop, bus, red\n\nExpected learner response\nBlends the word in one smooth sweep after building it.\n\nDifferentiation ideas\nStart with two-sound words; supply the first letter; use picture support.\n\nExtension activity\nLearner writes each word and draws a matching picture.",
  },
  {
    id: "a2",
    title: "Base-Ten Builders: Numbers to 1 000",
    grade: "Grade 4",
    subject: "Mathematics",
    skill: "Place value",
    difficulty: "Beginning",
    type: "Number games",
    content:
      "Learning objective\nThe learner represents 3-digit numbers as hundreds, tens and ones.\n\nMaterials required\nBase-ten blocks or bundled straws, place-value mat, dice.\n\nInstructions\n1. Roll three dice to make a 3-digit number.\n2. Build the number on the mat and say it aloud.\n3. Write it in expanded notation (e.g. 300 + 40 + 6).\n\nExample questions\n346, 508, 720, 199\n\nExpected learner response\nBuilds, says and writes the number correctly.\n\nDifferentiation ideas\nUse 2-digit numbers first; provide a filled example.\n\nExtension activity\nMake the largest and smallest number from the same three digits.",
  },
];

export const demoProgress: ProgressEntry[] = [
  {
    id: "pr1",
    learnerId: "l1",
    date: "05 Aug 2026",
    skill: "Blending",
    activity: "Sound boxes",
    performance: 45,
    prompting: "Frequent",
    successes: "Built 4 of 10 words",
    challenges: "Needed each sound repeated",
    nextSteps: "Continue with 2-sound words",
  },
  {
    id: "pr2",
    learnerId: "l1",
    date: "12 Aug 2026",
    skill: "Blending",
    activity: "Word family flashcards",
    performance: 60,
    prompting: "Occasional",
    successes: "Read the -at family independently",
    challenges: "Still reverses b/d",
    nextSteps: "Add tactile b/d sorting",
  },
  {
    id: "pr3",
    learnerId: "l1",
    date: "17 Aug 2026",
    skill: "Blending",
    activity: "Paired reading",
    performance: 72,
    prompting: "Minimal",
    successes: "Blended 7 of 10 CVC words",
    challenges: "Pace drops in longer sentences",
    nextSteps: "Introduce CVCC words",
  },
  {
    id: "pr4",
    learnerId: "l2",
    date: "06 Aug 2026",
    skill: "Place value",
    activity: "Base-ten builds",
    performance: 30,
    prompting: "Frequent",
    successes: "Built 2-digit numbers",
    challenges: "Confused tens and hundreds",
    nextSteps: "Use place-value mat labels",
  },
  {
    id: "pr5",
    learnerId: "l2",
    date: "13 Aug 2026",
    skill: "Place value",
    activity: "Place-value dice game",
    performance: 42,
    prompting: "Moderate",
    successes: "Named hundreds correctly",
    challenges: "Expanded notation errors",
    nextSteps: "Model expanded notation",
  },
  {
    id: "pr6",
    learnerId: "l2",
    date: "18 Aug 2026",
    skill: "Place value",
    activity: "Number-line jumps",
    performance: 55,
    prompting: "Occasional",
    successes: "3 of 5 builds correct",
    challenges: "Regrouping in subtraction",
    nextSteps: "Practise regrouping with blocks",
  },
];

export const demoReports: Report[] = [
  {
    id: "r1",
    learnerId: "l1",
    date: "17 Aug 2026",
    content:
      "Learner progress\nAmara has grown noticeably in her reading of short words this term. She now blends most three-sound words with only light support.\n\nCurrent strengths\nAmara listens attentively, enjoys shared reading and remembers stories in detail.\n\nAreas for continued development\nShe still benefits from support when telling b and d apart and when spelling everyday words.\n\nNext steps\nWe will continue short daily blending practice and add playful letter-sorting games.",
  },
];