/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as LearningChecksRouteImport } from './routes/learning-checks'
import { Route as LearningPlansRouteImport } from './routes/learning-plans'
import { Route as ParentCommunicationRouteImport } from './routes/parent-communication'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LearnersIndexRouteImport } from './routes/learners.index'
import { Route as LearnersLearnerIdRouteImport } from './routes/learners.$learnerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningChecksRoute = LearningChecksRouteImport.update({
  id: '/learning-checks',
  path: '/learning-checks',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPlansRoute = LearningPlansRouteImport.update({
  id: '/learning-plans',
  path: '/learning-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentCommunicationRoute = ParentCommunicationRouteImport.update({
  id: '/parent-communication',
  path: '/parent-communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersIndexRoute = LearnersIndexRouteImport.update({
  id: '/learners/',
  path: '/learners/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnersLearnerIdRoute = LearnersLearnerIdRouteImport.update({
  id: '/learners/$learnerId',
  path: '/learners/$learnerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/learning-checks': typeof LearningChecksRoute
  '/learning-plans': typeof LearningPlansRoute
  '/parent-communication': typeof ParentCommunicationRoute
  '/progress': typeof ProgressRoute
  '/learners/$learnerId': typeof LearnersLearnerIdRoute
  '/learners/': typeof LearnersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/learning-checks': typeof LearningChecksRoute
  '/learning-plans': typeof LearningPlansRoute
  '/parent-communication': typeof ParentCommunicationRoute
  '/progress': typeof ProgressRoute
  '/learners/$learnerId': typeof LearnersLearnerIdRoute
  '/learners': typeof LearnersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/learning-checks': typeof LearningChecksRoute
  '/learning-plans': typeof LearningPlansRoute
  '/parent-communication': typeof ParentCommunicationRoute
  '/progress': typeof ProgressRoute
  '/learners/$learnerId': typeof LearnersLearnerIdRoute
  '/learners/': typeof LearnersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/learning-checks'
    | '/learning-plans'
    | '/parent-communication'
    | '/progress'
    | '/learners/$learnerId'
    | '/learners/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/learning-checks'
    | '/learning-plans'
    | '/parent-communication'
    | '/progress'
    | '/learners/$learnerId'
    | '/learners'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/learning-checks'
    | '/learning-plans'
    | '/parent-communication'
    | '/progress'
    | '/learners/$learnerId'
    | '/learners/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  LearningChecksRoute: typeof LearningChecksRoute
  LearningPlansRoute: typeof LearningPlansRoute
  ParentCommunicationRoute: typeof ParentCommunicationRoute
  ProgressRoute: typeof ProgressRoute
  LearnersLearnerIdRoute: typeof LearnersLearnerIdRoute
  LearnersIndexRoute: typeof LearnersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-checks': {
      id: '/learning-checks'
      path: '/learning-checks'
      fullPath: '/learning-checks'
      preLoaderRoute: typeof LearningChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-plans': {
      id: '/learning-plans'
      path: '/learning-plans'
      fullPath: '/learning-plans'
      preLoaderRoute: typeof LearningPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-communication': {
      id: '/parent-communication'
      path: '/parent-communication'
      fullPath: '/parent-communication'
      preLoaderRoute: typeof ParentCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners/': {
      id: '/learners/'
      path: '/learners'
      fullPath: '/learners/'
      preLoaderRoute: typeof LearnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learners/$learnerId': {
      id: '/learners/$learnerId'
      path: '/learners/$learnerId'
      fullPath: '/learners/$learnerId'
      preLoaderRoute: typeof LearnersLearnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  LearningChecksRoute: LearningChecksRoute,
  LearningPlansRoute: LearningPlansRoute,
  ParentCommunicationRoute: ParentCommunicationRoute,
  ProgressRoute: ProgressRoute,
  LearnersLearnerIdRoute: LearnersLearnerIdRoute,
  LearnersIndexRoute: LearnersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
